### ISSUE TITLE
grunt-p4 not found.

### ISSUE THREAD

**Issue by royjacob** [shutterfly/grunt-p4#1]
Added it to my package file AND also tried 'npm install grunt-p4. 
Files are all there in the local node_modules library, but for some reason grunt won't find it.

Interestingly WebStorm's grunt tool does not even list the task.
gruntfile.js:
...some other tasks
    p4edit: {
      options: {
        preview: false,
        paths: ['wibble']
      }
    }
 });
![image](https://cloud.githubusercontent.com/assets/5317719/2858846/7e0583dc-d192-11e3-84b3-a60a2b797333.png)

**Comment by scottydawg** [comment]
Hy Roy, thanks for the heads up. I'm looking into it, should have a fix tomorrow.
